### PR TITLE
Add support for vanilla Linux kernel 6.2

### PR DESCRIPTION
**Pull request by Mixaill**
As of Linux Kernel 6.2, it now has an xmm7360-pci compatible interface
https://github.com/torvalds/linux/commit/d08b0f8f46e45a274fc8c9a5bc92cb9da70d9887

This PR adds enumeration of possible paths of XMM RPC interfaces.

### CODE REVIEW

**Comment by tgxn** [comment]
awesome, this looks good! by the looks it just loops though those interfaces till it finds the right one, could it check the existing `/dev/xmm0/rpc` first though?

**Comment by tgxn** [comment]
Does the new XMM interface mean that this will be more reliable, or just a different interface for this kind of thing?

Edit: ahh the pipes are broken too 🙄

**Comment by pswiatki** [comment]
Does it mean one can now use the kernel's own `iosm` with RPC support for `xmm7360` (and therefore only use the Python scripts from this `xmm7360-pci` project to bring the network interface up or shut it down?

**Comment by Mixaill** [comment]
@tgxn I've changed the order to prefer this repo over vanilla kernel

**Comment by Mixaill** [comment]
@pswiatki 

Yeah, starting with Linux 6.2 you can use the vanilla `iosm` using only the `lte.sh` script. 

Alternatively, you can use the fork of ModemManager https://gitlab.freedesktop.org/ShaneParslow/ModemManager/-/tree/enz7360

**Comment by pswiatki** [comment]
Oh! Thank you so much for the information, @Mixaill !! I will try `iosm` and possibly the fork of NM shortly after (when I know for sure `iosm` works nicely for me).

**Comment by tgxn** [comment]
One more thing - Can you pull this up-to-date with `master` for me? I just pushed a fix for the pipelines. Will merge once they pass :D

**Comment by Mixaill** [comment]
@tgxn rebased on top of master

**Comment by tgxn** [comment]
thanks @Mixaill <3

**Pull request merged**
