### PR TITLE
C Code Formatting + CI Workflow

### PR DESCRIPTION
**Pull request by tgxn**
replaces https://github.com/xmm7360/xmm7360-pci/pull/77 due to force pull from master required

### CODE REVIEW

**Comment by tgxn** [comment]
Tested, working well!

**Comment by malikkirchner** [comment]
@tgxn, thank you for merging the changes!

**Comment by zhuyifei1999** [comment]
I'm thinking. This is a kernel module. Wouldn't it make more sense to conform to the [kernel coding style](https://www.kernel.org/doc/html/latest/process/coding-style.html), if there are ever plans to mainline the driver?

**Comment by tgxn** [comment]
Hey @zhuyifei1999 Yeah I would probably agree with following that style guide might be the winning idea.

I don't think there's any plans to mainline this driver, unless someone else would like to. It's currently fairly hacky to bring it up/down, and ideally we'd have suspend/resume handling for it too.

**Comment by tgxn** [comment]
See #85

**Comment by zhuyifei1999** [comment]
> I don't think there's any plans to mainline this driver, unless someone else would like to. It's currently fairly hacky to bring it up/down, and ideally we'd have suspend/resume handling for it too.

I could try this when I get to it. No promises since device drivers isn't my area of expertise.

**Comment by tgxn** [comment]
No expectations here mate, the project had been inactive for ~14 months+ and I've just got access to start merging things in.

The driver works so it's not really a problem for people to manually load it when they need to, though obviously suspend/resume and stuff that makes it easier to load would be great.

**Pull request merged**
