### PR TITLE
Update .clang-format configuration to match linux kernel.

### PR DESCRIPTION
**Pull request by tgxn**
https://github.com/xmm7360/xmm7360-pci/pull/78#issuecomment-805531157

### CODE REVIEW

**Comment by tgxn** [comment]
Things brings the `.clang-format` in-line with the linux kernal modules.

**Comment by zhuyifei1999** [comment]
Uncommenting the `# Unknown to clang-format-*` ones, formatting again, I get:

```diff
$ diff -u xmm7360.c <(clang-format xmm7360.c)
--- xmm7360.c	2021-03-24 14:07:38.011260181 -0500
+++ /dev/fd/63	2021-03-24 14:09:32.750525774 -0500
@@ -409,9 +409,9 @@
 	ring->pages_phys = kzalloc(sizeof(dma_addr_t) * depth, GFP_KERNEL);
 
 	for (i = 0; i < depth; i++) {
-		ring->pages[i] =
-			dma_alloc_coherent(xmm->dev, ring->page_size,
-					   &ring->pages_phys[i], GFP_KERNEL);
+		ring->pages[i] = dma_alloc_coherent(xmm->dev, ring->page_size,
+						    &ring->pages_phys[i],
+						    GFP_KERNEL);
 		ring->tds[i].addr = ring->pages_phys[i];
 	}
 
@@ -730,14 +730,14 @@
 	return -ENOTTY;
 }
 
-static struct file_operations xmm7360_fops = { .read = xmm7360_cdev_read,
-					       .write = xmm7360_cdev_write,
-					       .poll = xmm7360_cdev_poll,
-					       .unlocked_ioctl =
-						       xmm7360_cdev_ioctl,
-					       .open = xmm7360_cdev_open,
-					       .release =
-						       xmm7360_cdev_release };
+static struct file_operations xmm7360_fops = {
+	.read = xmm7360_cdev_read,
+	.write = xmm7360_cdev_write,
+	.poll = xmm7360_cdev_poll,
+	.unlocked_ioctl = xmm7360_cdev_ioctl,
+	.open = xmm7360_cdev_open,
+	.release = xmm7360_cdev_release
+};
 
 static void xmm7360_mux_frame_init(struct xmm_net *xn, struct mux_frame *frame,
 				   int sequence)
@@ -1530,8 +1530,8 @@
 		TTY_DRIVER_REAL_RAW |
 		TTY_DRIVER_DYNAMIC_DEV; // Could this flags be defined in the flags??
 	xmm7360_tty_driver->init_termios = tty_std_termios;
-	xmm7360_tty_driver->init_termios.c_cflag =
-		B115200 | CS8 | CREAD | HUPCL | CLOCAL;
+	xmm7360_tty_driver->init_termios.c_cflag = B115200 | CS8 | CREAD |
+						   HUPCL | CLOCAL;
 	xmm7360_tty_driver->init_termios.c_lflag &= ~ECHO;
 	xmm7360_tty_driver->init_termios.c_ispeed = 115200;
 	xmm7360_tty_driver->init_termios.c_ospeed = 115200;
```

```
$ diff -u mux.c <(clang-format mux.c)
```

**Comment by tgxn** [comment]
I just copied the configuration from [here](https://raw.githubusercontent.com/torvalds/linux/master/.clang-format) if they have commented lines, won't there be a reason for that?

**Comment by zhuyifei1999** [comment]
The file was added to mainline around April of 2018 (https://github.com/torvalds/linux/commit/d4ef8d3ff005c70f6c9e2ffea14cc65fc8fe328d). At the time llvm/clang 5 [was just released](https://releases.llvm.org/) (and clang 6 was under development) so I would assume backward compatibility to clang 4 (released Mar 2017) and clang 5 (released Mar 2018) were particularly important.

Thought now that you speak about it, I wonder if asking to get them uncommented in mainline make sense. Hmm...

**Comment by tgxn** [comment]
Yeah that's what I was thinking @zhuyifei1999 ! Why don't they update them to have better rules :')

I see that several other kernel modules seem to "base" their `.clang-format` on the same file, however some do modify to suit their needs.

I'm happy with whatever approach, but I would err on the side of using the format from the latest tip of kernel. _(the one I copied was updated ~28 days ago)_

**Comment by zhuyifei1999** [comment]
> I'm happy with whatever approach, but I would err on the side of using the format from the latest tip of kernel. (the one I copied was updated ~28 days ago)

Yeah, that's valid. I just checked and using that of the latest mainline would actually revert the changes:

```diff
$ wget https://raw.githubusercontent.com/torvalds/linux/master/.clang-format -O .clang-format -q
$ diff -u xmm7360.c.1 <(clang-format xmm7360.c.1)
--- xmm7360.c.1	2021-03-24 20:12:45.352710914 -0500
+++ /dev/fd/63	2021-03-24 20:13:04.387070093 -0500
@@ -409,9 +409,9 @@
 	ring->pages_phys = kzalloc(sizeof(dma_addr_t) * depth, GFP_KERNEL);
 
 	for (i = 0; i < depth; i++) {
-		ring->pages[i] = dma_alloc_coherent(xmm->dev, ring->page_size,
-						    &ring->pages_phys[i],
-						    GFP_KERNEL);
+		ring->pages[i] =
+			dma_alloc_coherent(xmm->dev, ring->page_size,
+					   &ring->pages_phys[i], GFP_KERNEL);
 		ring->tds[i].addr = ring->pages_phys[i];
 	}
 
@@ -730,14 +730,14 @@
 	return -ENOTTY;
 }
 
-static struct file_operations xmm7360_fops = {
-	.read = xmm7360_cdev_read,
-	.write = xmm7360_cdev_write,
-	.poll = xmm7360_cdev_poll,
-	.unlocked_ioctl = xmm7360_cdev_ioctl,
-	.open = xmm7360_cdev_open,
-	.release = xmm7360_cdev_release
-};
+static struct file_operations xmm7360_fops = { .read = xmm7360_cdev_read,
+					       .write = xmm7360_cdev_write,
+					       .poll = xmm7360_cdev_poll,
+					       .unlocked_ioctl =
+						       xmm7360_cdev_ioctl,
+					       .open = xmm7360_cdev_open,
+					       .release =
+						       xmm7360_cdev_release };
 
 static void xmm7360_mux_frame_init(struct xmm_net *xn, struct mux_frame *frame,
 				   int sequence)
@@ -1530,8 +1530,8 @@
 		TTY_DRIVER_REAL_RAW |
 		TTY_DRIVER_DYNAMIC_DEV; // Could this flags be defined in the flags??
 	xmm7360_tty_driver->init_termios = tty_std_termios;
-	xmm7360_tty_driver->init_termios.c_cflag = B115200 | CS8 | CREAD |
-						   HUPCL | CLOCAL;
+	xmm7360_tty_driver->init_termios.c_cflag =
+		B115200 | CS8 | CREAD | HUPCL | CLOCAL;
 	xmm7360_tty_driver->init_termios.c_lflag &= ~ECHO;
 	xmm7360_tty_driver->init_termios.c_ispeed = 115200;
 	xmm7360_tty_driver->init_termios.c_ospeed = 115200;
```

I sent an email to Miguel Ojeda (who maintains that file) asking if there are plans to uncomment them.

**Comment by tgxn** [comment]
Yep, just noticed your email to Miguel :) Sounds good, will see what happens with that.

Copying it here so I can remember this! 👍 

```
Hi Miguel

I was pushing for an out-of-tree driver I was using to adapt to the
upstream clang-format [1], and it was pointed out how many of its
rules were commented out due to clang-format version reasons. I'm
wondering, since you are the maintainer of that file, are there any
plans to uncomment them, and possibly also adding newly supported
rules since 2018?

I CC'ed Domenic whom I was talking to in the linked issue.

Thanks
YiFei Zhu

[1] https://github.com/xmm7360/xmm7360-pci/pull/85
```

**Comment by tgxn** [comment]
FWIW: 
```
tgxn@lenovo:/etc/x1_yoga/xmm7360-pci (split_dbus_library) $ clang-format --version
clang-format version 10.0.0-4ubuntu1
```

**Review by annejan — APPROVED** [review]
That `ForEachMacros` though . .

**Comment by tgxn** [comment]
Hey @zhuyifei1999 

I noticed the email chain has gone quiet, with Miguel seemingly quite busy. Looks like the minimum for the kernel is `clang-format version 10.01` though.

Thinking we upgrade our clang format to be compatible with 10 and merge this in? Then we can always patch from kernel version when they accept/patch those changes?

**Comment by zhuyifei1999** [comment]
> I'm not 100% sure which lines are compatible/not with v10.01, maybe there's something we can copy already committed somewhere?

I'd suggest just uncomment the "# Unknown to clang-format-something" ones. If upstream would like to add new rules later we can see what they add and adapt.

**Comment by tgxn** [comment]
Okay, I've just uncommented [all of the commented lines](https://github.com/xmm7360/xmm7360-pci/pull/85/commits/00a44caa522d40dc5af9f6d2322e21979e5fdd08), since they were all for versions 4.0 and 5.0.

There's still the massive `for_each macros`, though I think that's fine to leave as-is.

I also would like to add a GitHub Action to perform clang-format and lint, maybe in another PR.

**Pull request merged**
