### PR TITLE
Change xmm7360_tty_write_room to unsigned in xmm7360.c

### PR DESCRIPTION
**Pull request by nursoda**
Signed-off-by: Olav Seyfarth <nursoda@users.noreply.github.com>

### CODE REVIEW

**Comment by deelerke** [comment]
in the meantime please see my workaround in the issue section 

ccflags-y := -Wno-multichar **-Wno-incompatible-pointer-types**

**Comment by flokli** [comment]
Did this change across kernel versions?

If I apply this patch on 5.10, I get the following error:

```
error: builder for '/nix/store/yfn7nyi8zfrnxi469m3nhi6fmj7x2503-xmm7360-pci-unstable-2021-07-19.drv' failed with exit code 2;
       last 10 log lines:
       > /build/source/xmm7360.c:1322:16: error: initialization of 'int (*)(struct tty_struct *)' from incompatible pointer type 'unsigned int (*)(struct tty_struct *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >  1322 |  .write_room = xmm7360_tty_write_room,
       >       |                ^~~~~~~~~~~~~~~~~~~~~~
       > /build/source/xmm7360.c:1322:16: note: (near initialization for 'xmm7360_tty_ops.write_room')
       > cc1: some warnings being treated as errors
       > make[3]: *** [/nix/store/f3q21byc5my9cgd6f28vbzfhiz7x8rzz-linux-5.10.81-dev/lib/modules/5.10.81/source/scripts/Makefile.build:280: /build/source/xmm7360.o] Error 1
       > make[2]: *** [/nix/store/f3q21byc5my9cgd6f28vbzfhiz7x8rzz-linux-5.10.81-dev/lib/modules/5.10.81/source/Makefile:1822: /build/source] Error 2
       > make[1]: *** [/nix/store/f3q21byc5my9cgd6f28vbzfhiz7x8rzz-linux-5.10.81-dev/lib/modules/5.10.81/source/Makefile:185: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/f3q21byc5my9cgd6f28vbzfhiz7x8rzz-linux-5.10.81-dev/lib/modules/5.10.81/build'
       > make: *** [Makefile:9: default] Error 2
       For full logs, run 'nix log /nix/store/yfn7nyi8zfrnxi469m3nhi6fmj7x2503-xmm7360-pci-unstable-2021-07-19.drv'.
```

With 5.14 and 5.15 it seems to build…

**Comment by tgxn** [comment]
Hi,  I get the same error as @flokli from this, the error is the same form the CI task in https://github.com/xmm7360/xmm7360-pci/pull/159#issuecomment-1030765322

**Comment by zear** [comment]
Looks like the return type for `tty_write_room` has been changed in v5.14 (03b3b1a2405cc):
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20220204&id=03b3b1a2405ccd71570cd5ec1fe4abd7bb4891cb

**Comment by tgxn** [comment]
I can confirm the patch from [here](https://github.com/xmm7360/xmm7360-pci/pull/159#issuecomment-1031498317) resolves the issue building on my kernel.

**Pull request merged**
