### PR TITLE
Fix: Remove low latency setting on TTY port

### PR DESCRIPTION
**Pull request by tgxn**

### CODE REVIEW

**Comment by DerChaot** [comment]
I can confirm, that this branch fixes the build issue on 5.12 (I was using Manjaro, should be irrelevant) and I can still connect using the WWAN.

**Comment by zhuyifei1999** [comment]
Why not delete the line? They can always be recovered from git history if needed.

**Comment by tgxn** [comment]
> Why not delete the line? They can always be recovered from git history if needed.

Yeah I was just testing it worked.

**Comment by LEXUGE** [comment]
I am not sure why, but I did experience kernel panics on 5.12 with this PR.

**Review by m-kuhn — APPROVED** [review]
Works perfectly fine on Fedora 34 (5.12.7-300.fc34.x86_64)
Good work :+1:

**Comment by tgxn** [comment]
Superseded by !117 (which has a version check)

**Pull request closed without merging**
