### PR TITLE
add dependencies to readme

### PR DESCRIPTION
**Pull request by mbernasocchi**

### CODE REVIEW

**Comment by tgxn** [comment]
Ideally, I'd like to clean up the readme file a bit and layout the how-to and dependencies a bit more locally, as there's not a complete example in addition to this list, so a bit of duplication.

**Comment by mbernasocchi** [comment]
hey @tgxn great to see you back :) let me know if I can help out with something. I can help in Python but can only read C

**Comment by tgxn** [comment]
Hey @mbernasocchi Cheers, I'm just the new guy that's picked this up and wants to help move it forwards. :)

I have a Lenovo X1 Yoga Gen 7, but if you use this driver, you could help testing out any of the PR's and changes on whatever OS you use. (like the networkmanager one #66, or the simple management script I put together from a couple of other suggestions #73) 

Personally, I still have a few issues with this driver from time-to-time so I'd also like an official driver; but in the absence of that, maybe we can work on some fixes for common issues.
(there's also a [reversing](https://github.com/xmm7360/reversing) repo in the org that I've yet to have a good look into)

**Comment by mbernasocchi** [comment]
@tgxn yes, indeed I just realised that I was confused and the original author was @abrasive. Anyway, good you got commit rights!

**Pull request merged**
