### PR TITLE
open_xdatachannel

### PR DESCRIPTION
**Pull request by c3r34lk1ll3r**
Hi, I added some little features to `open_xdatachannel.py`.

The APN can be configured inside a config file, along with priority of the route. This should be useful if there are more interface (like WiFi and WWAN).

I also add some error handling, for example the `key_error` in  unsolicited messages and the already existing ip addr.

### CODE REVIEW

**Comment by abrasive** [comment]
I don't quite understand, why is everything folded into a `main()` function?

**Comment by abrasive** [comment]
Implemented your changes - including setting the route metric (why does netlink call it `priority` when lower is preferred??). Thanks very much!

**Comment by c3r34lk1ll3r** [comment]
> I don't quite understand, why is everything folded into a `main()` function?

Old habits :) Let me know if you need help in implement specific features (also reverse engineering the firmware). 

Thanks for your amazing work!

**Comment by abrasive** [comment]
I've more or less run out of time to work actively on this for the time being, but there's still a lot to do...  Probably top of the list in terms of usability is getting sensible behaviour across suspend/resume. I took a stab at this but cut it out in 2066cdb because it caused hangs on resume if queue pairs were open.

Other worthwhile features:

- Working out where to stick an APN password - probably needs some grubbing about in the FW to work out where all the different bits of the config command fan out to
- Other XMM7x60 support. eg. XMM7560 has a superset of the commands and responses, at least by name, and I did manage to pull the table from the firmware. (That modem is x86, microcode updates and all!) But I don't have one of those.
- Working out what's going on with the "it just doesn't work" cases, eg. #5, #10.
- Cleaning up (or rewriting) the RPC code now that it's clear how it all works... that thing is embarrassing.

**Comment by abrasive** [comment]
I'm jhl on Freenode (or in #xmm7360) if you feel like discussing these or other bits btw

**Comment by c3r34lk1ll3r** [comment]
I will start with the RPC code. The power management is little obscure for me right now. 

See you on IRC!

**Pull request closed without merging**
